// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-marketplace.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.55.0";
import { z } from "npm:zod@^3.25.76";
function db() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_marketplace_default = defineTool({
  name: "search_marketplace",
  title: "Search VisuStock marketplace",
  description: "Search approved products (photos, videos, audio, VFX, ebooks) on the VisuStock marketplace by keyword and optional filters. Returns titles, slugs, prices (USD), and product URLs.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword or phrase to search titles, descriptions, and tags."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20)."),
    max_price: z.number().min(0).optional().describe("Filter to products at or below this USD price."),
    only_free: z.boolean().optional().describe("If true, return only free items (price = 0).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit, max_price, only_free }) => {
    const supabase = db();
    let q = supabase.from("content_submissions").select("id, title, description, slug, price, tags, width, height, created_at").eq("status", "approved").or(`title.ilike.%${query}%,description.ilike.%${query}%`).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (only_free) q = q.eq("price", 0);
    else if (typeof max_price === "number") q = q.lte("price", max_price);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const results = (data ?? []).map((r) => ({
      id: r.id,
      title: r.title,
      slug: r.slug,
      price_usd: r.price ?? 0,
      url: r.slug ? `https://visustock.com/products/${r.slug}` : `https://visustock.com/products/${r.id}`,
      tags: r.tags ?? [],
      dimensions: r.width && r.height ? `${r.width}x${r.height}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { count: results.length, results }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.55.0";
import { z as z2 } from "npm:zod@^3.25.76";
function db2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get VisuStock product details",
  description: "Fetch full details for a single approved VisuStock product by its slug or UUID: title, description, price (USD), tags, dimensions, and canonical URL.",
  inputSchema: {
    slug_or_id: z2.string().trim().min(1).describe("Product slug (preferred) or UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug_or_id }) => {
    const supabase = db2();
    const isUuid = /^[0-9a-f-]{36}$/i.test(slug_or_id);
    const { data, error } = await supabase.from("content_submissions").select("id, title, description, slug, price, tags, width, height, created_at, status").eq("status", "approved").eq(isUuid ? "id" : "slug", slug_or_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found." }], isError: true };
    const product = {
      id: data.id,
      title: data.title,
      description: data.description,
      slug: data.slug,
      price_usd: data.price ?? 0,
      tags: data.tags ?? [],
      dimensions: data.width && data.height ? `${data.width}x${data.height}` : null,
      url: data.slug ? `https://visustock.com/products/${data.slug}` : `https://visustock.com/products/${data.id}`,
      created_at: data.created_at
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.55.0";
function db3() {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List VisuStock categories",
  description: "List all content categories on the VisuStock marketplace with their slugs and category page URLs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = db3();
    const { data, error } = await supabase.from("categories").select("id, name, slug, description").order("name");
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const categories = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      slug: c.slug,
      description: c.description ?? null,
      url: `https://visustock.com/s/categories/${c.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(categories, null, 2) }],
      structuredContent: { count: categories.length, categories }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "visustock-mcp",
  title: "VisuStock Marketplace",
  version: "0.1.0",
  instructions: "Tools to browse the VisuStock marketplace \u2014 a premium digital marketplace for stock photos, videos, audio, VFX, and ebooks. Use `search_marketplace` to find products by keyword (optionally filter by price or free-only), `get_product` for full details on a single product by slug or ID, and `list_categories` for the current category taxonomy. All prices are in USD. Product URLs point to https://visustock.com/products/{slug}.",
  tools: [search_marketplace_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
